#Server settings (ServerProperties)
server:
  port: 8080
  address: 127.0.0.1
  session:
    timeout: 30
  context-path: /

  #Tomcat specifics
  tomcat:
    accesslog:
      enabled: false
    protocol-header: x-forwarded-proto
    remote-ip-header: x-forwarded-for
    background-processor-delay: 30 #secs
    basedir:


#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/proddb
#    username: root
#   password: rascal