#Server settings (ServerProperties)
server:
  port: 8080
  address: 127.0.0.1
  session:
    timeout: 30
  context-path: /

  #Tomcat specifics
  tomcat:
    accesslog:
      enabled: false
    protocol-header: x-forwarded-proto
    remote-ip-header: x-forwarded-for
    background-processor-delay: 30 #secs
    basedir:


#spring:
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:./h2/h2db
#    username: root
#   password: rascal